### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by ghost** [sibbi77/openhab2-addons#3]
Hi,
first of all thanks for migrating the binding to OH3.
I copied the jar file to addons folder, activated the binding and the thing is listed as online:
![image](https://user-images.githubusercontent.com/77097811/103876704-496b7500-50d4-11eb-9dd8-60a63562e1d9.png)
but all values show NULL:
![image](https://user-images.githubusercontent.com/77097811/103876816-6c962480-50d4-11eb-8e17-5c4a1bbab398.png)
log file shows java error:
`2021-01-06 22:03:54.821 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.NoSuchMethodError: 'org.openhab.binding.ecotouch.internal.EcoTouchTags[] org.openhab.binding.ecotouch.internal.EcoTouchTags.values()'
        at org.openhab.binding.ecotouch.internal.EcoTouchHandler.lambda$1(EcoTouchHandler.java:184) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`
Could you please help me to find out what's wrong with my binding?
Regards
Stoffl

**Comment by sibbi77** [comment]
I'll have a look at it this evening.

**Comment by sibbi77** [comment]
This happens in my test installation:
```
21:16:11.450 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'ecotouch:geo:3281d1146a' changed from UNINITIALIZED to INITIALIZING
21:16:11.457 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'ecotouch:geo:3281d1146a' changed from INITIALIZING to UNKNOWN
21:16:11.461 [WARN ] [ommon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception: 
java.lang.NoSuchMethodError: 'org.openhab.binding.ecotouch.internal.EcoTouchTags[] org.openhab.binding.ecotouch.internal.EcoTouchTags.values()'
        at org.openhab.binding.ecotouch.internal.EcoTouchHandler.lambda$1(EcoTouchHandler.java:184) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
21:16:11.543 [INFO ] [hab.event.ThingStatusInfoChangedEvent] - Thing 'ecotouch:geo:3281d1146a' changed from UNKNOWN to ONLINE
```
This behaviour is normal (ähem...).
I'm not sure, why this could happen: first, the method .values() is a built in method of the language itself and second: this happens inside a try catch block, which should silence the warning.

Nevertheless, it is harmless. If your binding does not change to ONLINE, the IP is wrong or the username/password.

**Comment by ghost** [comment]
thanks for your investigation.
This isn't working since OH3 update, in OH2.5 it was working. I checked username, password and IP, can login to CAREL panel:
![image](https://user-images.githubusercontent.com/77097811/103943742-e78e2800-5132-11eb-9412-28391abbd9f8.png)
The only difference is java version, which I updated to 11. I use the zulu repository. I used zulu 8 before when it was mandatory for OH2.5.
Could using zulu be the reason why it doesn't work? Is there any possibility to debug and send you a log file?
Thanks for your support

**Comment by sibbi77** [comment]
please try the new pre-release: https://github.com/sibbi77/openhab2-addons/releases/tag/ecotouch-3.0.0-2

**Comment by ghost** [comment]
thanks you solved this issue, it's working with pre-release 3.0.0-2:
![image](https://user-images.githubusercontent.com/77097811/103949649-e1507980-513b-11eb-9a52-f558c8f4e088.png)
